baseURL = 'https://vraton.dev'
title = 'vraton.dev'
theme = 'rose-pine'
IsMultiLingual = true
languageCode = 'pt-br'
defaultContentLanguageInSubdir = false
defaultContentLanguage = "pt-br"

[languages]
[languages.en]
    languageCode = 'en'
    languageName = ':us:'

[languages.en.menus]
[[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'

[[languages.en.menus.main]]
        name = 'Posts'
        pageRef = '/posts'

[[languages.en.menus.main]]
        name = 'Tags'
        pageRef = '/tags'

[languages.pt-br]
    languageCode = 'pt-br'
    languageName = ':brazil:'

[languages.pt-br.menus]
[[languages.pt-br.menus.main]]
        name = 'Início'
        pageRef = '/'

[[languages.pt-br.menus.main]]
        name = 'Postagens'
        pageRef = '/posts'
[[languages.pt-br.menus.main]]
        name = 'Experiências'
        pageRef = '/experiences'
[[languages.pt-br.menus.main]]
        name = 'Tags'
        pageRef = '/tags'

[params]
description = "Victor Raton's personal space"
[[params.social]] 
    name = "Mastodon"
    url = "https://fosstodon.org/@v_raton"
[[params.social]] 
    name = "Github"
    url = "https://github.com/victorfernandesraton"
[[params.social]] 
    name = "Linkedin" 
    url = "https://linkedin.com/in/v_raton"




[taxonomies]
skills = 'skills'