baseURL = 'https://vraton.dev'
languageCode = 'en-US'
title = 'Blog tech do Raton'
theme = 'rose-pine'

[[params.social]] 
    name = "Mastodon"
    url = "https://fosstodon.org/@v_raton"
[[params.social]] 
    name = "Github"
    url = "https://github.com/victorfernandesraton"
[[params.social]] 
    name = "Linkedin" 
    url = "https://linkedin.com/in/v_raton"

